/** Canonical content — Breath of Innovation · July 8, 2026 */
window.BOI = {
  event: {
    title: "Breath of Innovation",
    date: "Tuesday, July 8, 2026",
    location: "Norco, California",
    arrival: "9:00 AM",
    arrivalNote: "Conference room across from The Flavor Factory",
    facility: "2058 Second Street, Norco, CA 92860",
    phone: "(951) 273-9877",
    web: "flavorfactory.net",
  },
  schedule: [
    { time: "9:00 AM", end: "10:00", title: "Presentation", desc: "Four pillars — open conversation", accent: "#008fd3" },
    { time: "10:00", end: "10:15", title: "Facility tour", desc: "Production, QC, TheraBreath room", accent: "#5fb832" },
    { time: "10:15", end: "10:30", title: "Break", desc: "Reset before tasting", accent: "#5c6678" },
    { time: "10:30", end: "11:15", title: "Tasting", desc: "Five prototypes · blind then score", accent: "#f58220" },
    { time: "11:30", end: "1:00", title: "Lunch off site", desc: "Your hosts take the group", accent: "#5b6b8a" },
    { time: "1:00 PM+", end: "", title: "Open Q&A", desc: "Your topics · your pace", accent: "#006da3" },
  ],
  pillars: [
    {
      id: "resiliency",
      num: 1,
      title: "Resiliency",
      tagline: "Protect the core as you grow.",
      color: "#008fd3",
      points: ["Capacity & growth scenarios", "SQF · GMP · FDA registered", "Alternate suppliers & continuity"],
    },
    {
      id: "innovation",
      num: 2,
      title: "Innovation",
      tagline: "Flavor work inside your products.",
      color: "#5fb832",
      points: ["Oral-care & chlorite chemistry", "Sensory science & prototypes", "Competitive & seasonal directions"],
    },
    {
      id: "operations",
      num: 3,
      title: "Operations",
      tagline: "One roof. Full visibility.",
      color: "#f58220",
      points: ["Norco dev + production + QC", "Batch release & traceability", "COAs & supplier documentation"],
    },
    {
      id: "partnership",
      num: 4,
      title: "Partnership",
      tagline: "Build together long term.",
      color: "#0a1628",
      points: ["Communication cadence", "Investment alignment", "Co-development roadmap"],
    },
  ],
  qaSections: [
    {
      pillar: "Resiliency & Business Continuity",
      pillarShort: "Pillar 1",
      num: 1,
      color: "#008fd3",
      intro: "Supply security, capacity, and continuity as TheraBreath grows.",
      cards: [
        {
          num: 1,
          question: "If TheraBreath doubles in volume over the next 3–5 years, how will TFF support that growth?",
          points: ["Built for headroom", "More shifts & equipment", "Invest as you grow"],
          answer: "We intentionally operate with room to grow. Our current infrastructure, staffing model, and production planning processes allow us to absorb significant growth. As demand increases, we can expand production schedules, add equipment, increase staffing, and continue investing in our facility to support TheraBreath's growth trajectory.",
        },
        {
          num: 2,
          question: "What happens if a key supplier becomes unavailable?",
          points: ["Secondary sources", "Critical inventory", "PG shortage lessons"],
          answer: "We actively manage supplier relationships and pursue secondary sourcing opportunities whenever possible. We maintain inventory visibility on critical materials and learned valuable lessons from recent supply chain disruptions, including the propylene glycol shortage. Our goal is to minimize risk before it becomes a problem.",
        },
        {
          num: 3,
          question: "What happens if a key employee is unavailable?",
          points: ["Cross-trained team", "No single point of failure", "Continuity by design"],
          answer: "Cross-training is a major focus at The Flavor Factory. Multiple team members are trained across production, warehousing, shipping, receiving, and quality functions. This reduces dependence on any one individual and helps ensure operational continuity.",
        },
        {
          num: 4,
          question: "How do you maintain quality as volume grows?",
          points: ["Full traceability", "Batch records", "Same specs, more scale"],
          answer: "Every ingredient, batch, and shipment is fully traceable. We maintain documented procedures, batch records, specification management, supplier qualification programs, and quality review processes to ensure consistency regardless of production volume.",
        },
        {
          num: 5,
          question: "How would TFF respond to a major disruption or disaster?",
          points: ["Contingency plans", "Backup capacity", "Supply continuity"],
          answer: "We maintain contingency plans, emergency manufacturing relationships, supplier redundancy efforts, and inventory controls designed to minimize business interruption and maintain continuity of supply whenever possible.",
        },
      ],
    },
    {
      pillar: "Innovation & Technical Capabilities",
      pillarShort: "Pillar 2",
      num: 2,
      color: "#5fb832",
      intro: "Flavor development, sensory science, and what's next for oral care.",
      cards: [
        {
          num: 6,
          question: "How does TFF stay ahead of flavor trends?",
          points: ["We bring ideas to you", "Watch ingredients & consumers", "Proactive, not reactive"],
          answer: "We continuously evaluate emerging flavor trends, ingredient technologies, consumer preferences, and supplier innovations. Our goal is to proactively bring ideas to TheraBreath rather than waiting to be asked.",
        },
        {
          num: 7,
          question: "Can TFF support products beyond today's mouthrinse portfolio?",
          points: ["Kids · gummies · powders", "Wellness & seasonal", "Future adjacencies"],
          answer: "Yes. Our development capabilities extend beyond mouthrinses into children's products, gummies, powders, wellness products, seasonal programs, and future oral care adjacencies.",
        },
        {
          num: 8,
          question: "How does TFF approach innovation?",
          points: ["Fast prototypes", "Your feedback loop", "Bench → production"],
          answer: "We combine creative flavor development with practical manufacturing expertise. Our team rapidly develops prototypes, gathers feedback, refines concepts, and works collaboratively with customers to accelerate innovation.",
        },
        {
          num: 9,
          question: "How does TFF validate sensory performance?",
          points: ["Triangle testing", "Consumer feedback", "University partners"],
          answer: "We are building structured sensory evaluation capabilities, including external triangle testing, consumer feedback collection, and university partnerships to better understand how consumers perceive product changes and innovations.",
        },
        {
          num: 10,
          question: "What innovation opportunities excite TFF most for TheraBreath?",
          points: ["Next-gen cooling", "Pediatric & wellness", "Seasonal & longevity"],
          answer: "Next-generation cooling systems, natural sweetness enhancement, pediatric oral care, wellness-focused products, seasonal concepts, and long-lasting freshness technologies represent exciting opportunities for future growth.",
        },
      ],
    },
    {
      pillar: "Operations",
      pillarShort: "Pillar 3",
      num: 3,
      color: "#f58220",
      intro: "Investments, service levels, and securing critical materials.",
      cards: [
        {
          num: 11,
          question: "What investments has TFF made to support TheraBreath?",
          points: ["Dedicated TB space", "Warehouse & process", "Quality systems"],
          answer: "Recent investments include facility improvements, warehouse organization, dedicated TheraBreath production space, process improvements, inventory controls, and ongoing investments in quality and operational systems.",
        },
        {
          num: 12,
          question: "How does TFF maintain service levels and lead times?",
          points: ["Proactive scheduling", "Close collaboration", "Flexible + reliable"],
          answer: "Through proactive production scheduling, inventory management, supplier communication, and close collaboration with customers. Our goal is to remain flexible while maintaining reliable service.",
        },
        {
          num: 13,
          question: "How does TFF secure critical raw materials?",
          points: ["Supplier relationships", "Alt sourcing", "Inventory visibility"],
          answer: "We actively manage supplier relationships, monitor inventory levels, evaluate alternative sourcing opportunities, and maintain visibility on critical ingredients to reduce supply risk.",
        },
      ],
    },
    {
      pillar: "Partnership & Growth Vision",
      pillarShort: "Pillar 4",
      num: 4,
      color: "#0a1628",
      intro: "Why TFF is the right long-term partner — and what success looks like.",
      cards: [
        {
          num: 14,
          question: "Why is TFF the right long-term partner for TheraBreath?",
          points: ["Responsive & flexible", "Technical depth", "We invest with you"],
          answer: "Because we combine responsiveness, flexibility, technical expertise, and personal commitment. We genuinely care about the success of the brands we support and are willing to invest alongside our customers.",
        },
        {
          num: 15,
          question: "What makes working with TFF different?",
          points: ["Direct to leadership", "Fast decisions", "Trust & transparency"],
          answer: "Direct access to leadership, fast decision-making, transparency, and a collaborative problem-solving approach. We believe strong partnerships are built on communication and trust.",
        },
        {
          num: 16,
          question: "What does success look like over the next 5 years?",
          points: ["Shared growth", "Innovation pipeline", "Resilient partnership"],
          answer: "A stronger, more resilient partnership that supports TheraBreath's continued growth through innovation, supply chain excellence, operational reliability, and shared long-term success.",
        },
      ],
    },
  ],
  strategicQuestions: [
    {
      num: 1,
      question: "What does success look like for TheraBreath in 3–5 years?",
      points: ["Align investments with brand direction", "Plan capacity & innovation together"],
      why: "Helps us align our investments and capabilities with the brand's future direction.",
    },
    {
      num: 2,
      question: "What are your biggest growth challenges?",
      points: ["Where TFF can help", "Obstacles to solve jointly"],
      why: "Identifies obstacles where TFF can provide support or solutions.",
    },
    {
      num: 3,
      question: "What separates your best suppliers from everyone else?",
      points: ["What great looks like", "Roadmap for partnership"],
      why: "Provides a roadmap for becoming a stronger strategic partner.",
    },
    {
      num: 4,
      question: "How can suppliers better support your resiliency goals?",
      points: ["Continuity expectations", "Supply security priorities"],
      why: "Reveals expectations around continuity planning and supply security.",
    },
    {
      num: 5,
      question: "What innovation opportunities excite you most?",
      points: ["Highest-value R&D focus", "Where to invest next"],
      why: "Focuses future development efforts on the highest-value opportunities.",
    },
    {
      num: 6,
      question: "What oral care trends are currently underappreciated?",
      points: ["Emerging opportunities", "Get ahead of competitors"],
      why: "Helps uncover emerging opportunities before competitors.",
    },
    {
      num: 7,
      question: "What sensory attributes matter most to consumers today?",
      points: ["Consumer priorities", "Guide flavor development"],
      why: "Guides flavor development and product experience decisions.",
    },
    {
      num: 8,
      question: "What could The Flavor Factory do to become an even stronger partner?",
      points: ["Honest feedback welcome", "How we improve"],
      why: "Creates an opportunity for honest feedback and improvement.",
    },
    {
      num: 9,
      question: "How would you like sensory validation data presented?",
      points: ["Actionable format", "Make testing useful"],
      why: "Ensures our testing efforts provide useful and actionable information.",
    },
    {
      num: 10,
      question: "After today's visit, what would make you most confident in our ability to support future growth?",
      points: ["Address remaining concerns", "End on what builds confidence"],
      why: "Reveals any remaining concerns and focuses attention on what matters most.",
    },
  ],
  chapters: null,
};