/**
 * Master flavor portfolio — TFF × Church & Dwight × TheraBreath.
 */
(function (global) {
  var COLLECTIONS = {
    production: { id: "production", label: "In Production", count: 14, color: "#0d9488", desc: "TheraBreath SKUs greenlit and on shelf — mapped to TFF flavor codes and usage levels." },
    presented: { id: "presented", label: "Concepts Presented", count: 29, color: "#008fd3", desc: "Heritage Top 8 and C&D storytelling flavors sent for review — not selected for production." },
    pipeline: { id: "pipeline", label: "Pipeline", count: 5, color: "#5fb832", desc: "July 8 workshop mint platforms (M1–M5) — chlorite-aware prototypes in active development." },
    genalpha: { id: "genalpha", label: "Gen Alpha", count: 5, color: "#6c5ce7", desc: "Social-first futures — scroll-stopping shelf stories." }
  };

  var SEASONS = {
    summer: { label: "Spring / Summer", color: "#e85d8a" },
    winter: { label: "Fall / Winter", color: "#c45c26" },
    stable: { label: "Stable", color: "#5fb832" },
    innovation: { label: "Innovation", color: "#008fd3" },
    future: { label: "Future", color: "#6c5ce7" },
    production: { label: "On Shelf", color: "#0d9488" }
  };

  var concepts = [
    { slug: "clean-mint", name: "Clean Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "MI-18727", usage: "1.00%",
      positioning: "TheraBreath core rinse · everyday fresh",
      story: "Crisp, balanced peppermint-spearmint freshness — the everyday TheraBreath signature consumers know and trust.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "dazzling-mint", name: "Dazzling Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "MI-20300", usage: "0.10%",
      positioning: "Whitening-positioned rinse · bright mint",
      story: "Bright peppermint with sparkling icy character — aligned with TheraBreath whitening sub-line positioning.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "invigorating-icy-mint", name: "Invigorating Icy Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "PE-05523", usage: "0.10%",
      positioning: "Hero cooling SKU · extra-icy rinse",
      story: "Peak cooling peppermint with extended icy lift — built for consumers who want maximum fresh intensity.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "mild-mint", name: "Mild Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "PE-05523", usage: "0.03%",
      positioning: "Gentle everyday rinse · sensitive-friendly",
      story: "Soft spearmint-peppermint balance at a lighter usage level — approachable fresh for daily rinsing.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "overnight-rinse", name: "Overnight", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "CH-21205", usage: "0.275%",
      positioning: "PM calm rinse · evening ritual",
      story: "Soft chamomile-mint calm built for overnight protection — gentle character for bedtime rinsing.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "rainforest-mint", name: "Rainforest Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "TR-19125 · TR-19123 · PE-05523", usage: "0.32% citrus · 0.21% bergamot · 0.075% mint base",
      positioning: "Botanical mint · citrus-bergamot complexity",
      story: "Layered rainforest character — bright citrus top, aromatic bergamot mid, and a clean mint close.",
      note: "Multi-component flavor system · active SKU" },
    { slug: "revitalizing-mint", name: "Revitalizing Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "MI-21336", usage: "0.3%",
      positioning: "Complete rinse · 6-in-1 multi-benefit",
      story: "Clinical-fresh mint character for TheraBreath Complete Revitalizing Mint — balanced therapeutic fresh for gum-health positioning.",
      note: "Nat Total Care Mint Flavor · MI-21336 · active SKU" },
    { slug: "sparkle-mint", name: "Sparkle Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "PE-05523", usage: "0.05%",
      positioning: "Light sparkle fresh · subtle cooling",
      story: "Delicate peppermint sparkle at a lower usage level — bright without overwhelming intensity.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "tingling-mint", name: "Tingling Mint", collection: "production", season: "production",
      tag: "IN PRODUCTION · ON SHELF", status: "in_production",
      tffCode: "PE-05523", usage: "0.10%",
      positioning: "Tingling fresh · sensory intensity",
      story: "Peppermint-forward cooling with a distinctive tingling sensation — a step up from everyday mild mint.",
      note: "Active SKU · per C&D flavor usage specification" },
    { slug: "bubble-gum", name: "Bubble Gum", collection: "production", season: "production",
      tag: "IN PRODUCTION · KIDS", status: "in_production",
      tffCode: "BG-21663", usage: "0.75%",
      positioning: "Kids rinse · classic bubblegum",
      story: "Nostalgic bubblegum sweetness balanced with peppermint snap — fun first, fresh always.",
      note: "Kids Rinse SKU · active production" },
    { slug: "grapes-galore", name: "Grapes Galore", collection: "production", season: "production",
      tag: "IN PRODUCTION · KIDS", status: "in_production",
      tffCode: "GR-17309", usage: "0.50%",
      positioning: "Kids rinse · grape candy fresh",
      story: "Playful Concord grape sweetness snapped shut by a clean mint finish — kid-approved without sacrificing oral-care credibility.",
      note: "Kids Rinse SKU · active production" },
    { slug: "strawberry-splash", name: "Strawberry Splash", collection: "production", season: "production",
      tag: "IN PRODUCTION · KIDS", status: "in_production",
      tffCode: "ST-20913", usage: "0.60%",
      positioning: "Kids rinse · berry bright",
      story: "Ripe strawberry splash with clean mint close — bright, approachable, and built for repeat rinsing.",
      note: "Kids Rinse SKU · active production" },
    { slug: "wacky-watermelon", name: "Wacky Watermelon", collection: "production", season: "production",
      tag: "IN PRODUCTION · KIDS", status: "in_production",
      tffCode: "WA-20912", usage: "0.60%",
      positioning: "Kids rinse · summer fruit fun",
      story: "Juicy watermelon freshness with a mint stabilizer — pool-party energy in a kid-friendly capful.",
      note: "Kids Rinse SKU · active production" },
    { slug: "peppermint-vanilla", name: "Peppermint Vanilla", collection: "production", season: "production",
      tag: "IN PRODUCTION · SEASONAL GREENLIT", status: "in_production",
      tffCode: "62012072", usage: "Per seasonal formulation",
      positioning: "Seasonal LE · C&D selected from TFF presentation",
      story: "Warm vanilla creaminess wrapped in classic peppermint — TheraBreath's greenlit seasonal pick from the flavors we presented.",
      note: "Nat Peppermint Vanilla Type FL · greenlit Dec 2025 · PE-22004 legacy reference" },

    { slug: "hibiscus-lemonade", name: "Hibiscus Lemonade", collection: "presented", season: "summer",
      tag: "PRESENTED · HERITAGE · SPRING / SUMMER",
      positioning: "Seasonal LE · floral-bright · garden-party",
      story: "Imagine a relaxed summer afternoon in a sunlit garden. Soft petals of vibrant hibiscus flowers float gracefully atop ice-cold glasses filled with pink lemonade, beads of condensation slowly gliding down the sides. Gentle sunlight filters through lush greenery and blooming flowers, evoking tranquility, elegance, and the sophisticated refreshment of a leisurely summer day.",
      note: "Long-form heritage storytelling · floral top over mint-fresh base" },
    { slug: "raspberry-mint-lemonade", name: "Raspberry Mint Lemonade", collection: "presented", season: "summer",
      tag: "PRESENTED · HERITAGE · SPRING / SUMMER",
      positioning: "Social refresh · brunch & patio",
      story: "Picture an inviting outdoor brunch, nestled in the shade of tall trees. Bright raspberries and fresh mint leaves garnish glasses filled with sparkling lemonade, creating a vivid contrast of red and green against crystal-clear ice.",
      note: "Mint anchor stabilizes berry brightness" },
    { slug: "cherry-limeade", name: "Cherry Limeade", collection: "presented", season: "summer",
      tag: "PRESENTED · HERITAGE · SPRING / SUMMER",
      positioning: "Nostalgic energy · picnic occasion",
      story: "Visualize a lively, yet nostalgic scene—friends gathered around a picnic table draped in a classic checkered cloth. Mason jars filled with vibrant cherry limeade glisten under golden sunshine, garnished playfully with cherries and wedges of zesty lime.",
      note: "Citrus-cherry innovation lane · seasonal LE" },
    { slug: "berry-melon", name: "Berry Melon", collection: "presented", season: "summer",
      tag: "PRESENTED · HERITAGE · SPRING / SUMMER",
      positioning: "Peak summer · farmers-market vitality",
      story: "Envision a farmers' market at the height of summer: stalls overflowing with fresh berries nestled next to juicy, vibrant slices of melon. Sunlight dances through market umbrellas, highlighting lush abundance.",
      note: "Mixed-fruit · retain review beyond seasonal LE" },
    { slug: "cinnamon-mint", name: "Cinnamon Mint (Cinnamint)", collection: "presented", season: "winter",
      tag: "PRESENTED · HERITAGE · FALL / WINTER",
      positioning: "Holiday warmth · cozy morning ritual",
      story: "Picture yourself in a cozy cabin on a crisp winter morning, the landscape outside dusted gently with snow. Steam rises from a warmly spiced beverage garnished with cinnamon sticks and fresh mint leaves.",
      note: "Spice-mint · chlorite-friendly fall LE" },
    { slug: "wintergreen-spice", name: "Wintergreen Spice", collection: "presented", season: "winter",
      tag: "PRESENTED · HERITAGE · FALL / WINTER",
      positioning: "Fireside calm · cool-warm contrast",
      story: "Imagine a tranquil evening beside a crackling fireplace. Aromas of fresh wintergreen mingle with gentle spices, filling the room with warmth and clarity. Outside, snow quietly blankets the landscape.",
      note: "Wintergreen proven in oral care" },
    { slug: "honey-ginger", name: "Honey-Ginger", collection: "presented", season: "winter",
      tag: "PRESENTED · HERITAGE · FALL / WINTER",
      positioning: "Wellness cue · soothing evening",
      story: "Visualize a calming evening indoors, soft golden candlelight illuminating a warmly decorated kitchen. Honey slowly drizzles from a spoon as freshly sliced ginger steeps nearby — calm indulgence and luxurious freshness.",
      note: "Included once across master book · ginger stability path in chlorite" },
    { slug: "pomegranate-ginger", name: "Pomegranate Ginger", collection: "presented", season: "winter",
      tag: "PRESENTED · HERITAGE · FALL / WINTER",
      positioning: "Festive premium · holiday entertaining",
      story: "Picture an elegant holiday gathering, softly illuminated by twinkling lights. Glasses garnished with vibrant pomegranate seeds and sliced ginger glow warmly in the festive atmosphere.",
      note: "Distinct from RW Pomegranate-Pear · holiday LE flagship" },

    { slug: "watermelon-mojito", name: "Watermelon Mojito", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Refreshing, lively, and energizing — sunny afternoons and social gatherings.",
      positioning: "Peak summer LE · patio & pool",
      story: "Juicy watermelon with a mint-lime snap — poolside energy in a capful.",
      note: "Mint-lime chassis · fruit top over cooling base" },
    { slug: "pink-lemonade", name: "Pink Lemonade", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Carefree moments, nostalgic summers, and vibrant freshness.",
      positioning: "Nostalgia LE · carefree summer",
      story: "Soft pink lemonade nostalgia with a clean adult finish — carnival memory without the sugar crash.",
      note: "Lemon brightness · mint stabilizer for chlorite" },
    { slug: "strawberry-basil", name: "Strawberry Basil", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Sophisticated freshness — classic sweetness with a modern herbal twist.",
      positioning: "Premium tier · beauty-counter fresh",
      story: "Ripe strawberry cut by fresh basil — farmers-market sophistication for consumers who want interesting, not loud.",
      note: "Herbal-strawberry · Gen Alpha crossover" },
    { slug: "peach-tea", name: "Peach Tea", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Leisurely refreshment and the charm of a peaceful summer day.",
      positioning: "Afternoon calm · tea-house",
      story: "Sun-warmed peach over soft iced tea — porch-swing calm in liquid form.",
      note: "Distinct from pipeline Fresh Herbal Mint" },
    { slug: "cucumber-melon", name: "Cucumber Melon", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Soothing wellness and rejuvenation — serene summer retreat.",
      positioning: "Spa wellness · calm fresh",
      story: "Cool cucumber water meets honeydew-soft melon — spa-day serenity that still feels fresh.",
      note: "Workshop cucumber direction · retain review" },
    { slug: "peppermint-mocha", name: "Peppermint Mocha", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Warmth, indulgence, festive cheer, and comforting freshness.",
      positioning: "Holiday LE · coffeehouse",
      story: "Coffeehouse peppermint mocha warmth with a clean mint exhale — holiday indulgence that still freshens.",
      note: "Chocolate-mint · seasonal only" },
    { slug: "ginger-lime-mule", name: "Ginger + Lime Mule", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Sophistication, festive energy, and vibrant freshness.",
      positioning: "Holiday entertaining · cocktail cue",
      story: "Copper-mug ginger bite with bright lime lift — cocktail sophistication translated to oral care.",
      note: "Distinct from Honey-Ginger and pipeline Immunity Mint" },
    { slug: "spiced-apple-cider", name: "Crisp Apple / Spiced Apple Cider", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Warmth, comfort, authenticity, and crisp autumn nostalgia.",
      positioning: "Autumn flagship · orchard LE",
      story: "Orchard-crisp apple wrapped in gentle baking spice — autumn walks in a bottle.",
      note: "Spice-apple architecture" },
    { slug: "cranberry-lime", name: "Cranberry Lime", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Bright freshness, celebration, and crisp festive energy.",
      positioning: "Winter holidays · gathering fresh",
      story: "Tart cranberry sparkle with lime brightness — Thanksgiving-to-New-Year table fresh.",
      note: "Berry-lime innovation lane" },
    { slug: "pumpkin-spice", name: "Pumpkin Spice", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Seasonal comfort, indulgent freshness, and cozy fall-winter nostalgia.",
      positioning: "October LE · cozy comfort",
      story: "Cinnamon, nutmeg, and clove warmth with a surprisingly clean finish — October's expected flavor, built for oral care.",
      note: "Proven retail velocity anchor" },

    { slug: "strawberry-pineapple", name: "Strawberry-Pineapple", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Carefree summer getaway, vibrant energy, and relaxation.",
      positioning: "Vacation energy · travel occasion",
      story: "Sun-warmed strawberry meets bright pineapple — vacation in a capful.",
      note: "Fruit-forward · mint stabilizer for chlorite" },
    { slug: "orange-creamsicle", name: "Orange Creamsicle", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Childhood memories with adult sophistication.",
      positioning: "Nostalgia play · summer LE",
      story: "Creamy vanilla-orange nostalgia with a clean, grown-up finish.",
      note: "Cream + citrus · innovation lane" },
    { slug: "blueberry-lemon", name: "Blueberry-Lemon", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Relaxation, rejuvenation, and fresh morning energy.",
      positioning: "Morning refresh · daily ritual",
      story: "Morning-bright lemon lifts deep blueberry richness — spa-water clarity.",
      note: "Berry character · retain review" },
    { slug: "coconut-lime", name: "Coconut-Lime", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Calm, tropical indulgence, relaxation, and escape.",
      positioning: "Tropical calm · resort self-care",
      story: "Creamy coconut softened by zesty lime — beach calm without sunscreen sweetness.",
      note: "Covers coconut platform for Gen Alpha" },
    { slug: "mango-berry", name: "Mango-Berry", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Natural goodness and abundance for an energetic lifestyle.",
      positioning: "Active lifestyle · vibrant daily",
      story: "Ripe mango folded into mixed berry depth — farmers-market abundance.",
      note: "Mixed fruit · directional tasting" },
    { slug: "dragonfruit-rose", name: "Dragonfruit-Rose", collection: "presented", season: "summer",
      tag: "PRESENTED · SPRING / SUMMER", feel: "Refined freshness, serenity, luxury, and elevated personal care.",
      positioning: "Premium tier · beauty counter · Gen Alpha crossover",
      story: "Exotic dragonfruit with a whisper of rose — premium, photogenic, skincare-adjacent oral care.",
      note: "Covers dragonfruit platform" },
    { slug: "vanilla-hazelnut", name: "Vanilla-Hazelnut", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Comfort, warmth, and indulgence in colder seasons.",
      positioning: "Cozy indulgence · AM ritual",
      story: "Toasted hazelnut and warm vanilla — coffeehouse comfort in a rinse.",
      note: "Nutty-vanilla · more stable than citrus" },
    { slug: "toasted-marshmallow", name: "Toasted Marshmallow", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Community, warmth, nostalgia, and cozy companionship.",
      positioning: "Holiday LE · campfire nostalgia",
      story: "Campfire marshmallow toastiness with a clean snap finish.",
      note: "Sweet gourmand · seasonal only" },
    { slug: "carrot-cake", name: "Carrot Cake", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Comfort, nostalgia, and freshly baked seasonal treats.",
      positioning: "Bakery nostalgia · autumn LE",
      story: "Spiced carrot cake warmth — cinnamon, vanilla, and baked comfort.",
      note: "Spice-vanilla architecture" },
    { slug: "blackberry-lavender", name: "Blackberry-Lavender", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Sophisticated calmness, relaxation, and seasonal tranquility.",
      positioning: "PM calm · spa-evening",
      story: "Dark blackberry richness softened by lavender calm — evening-rinse sophistication.",
      note: "Floral-berry · retain review" },
    { slug: "pomegranate-pear", name: "Pomegranate-Pear", collection: "presented", season: "winter",
      tag: "PRESENTED · FALL / WINTER", feel: "Festive sophistication and crisp winter celebration.",
      positioning: "Holiday premium · entertaining",
      story: "Tart pomegranate with crisp pear brightness — holiday sparkle without cloying sweetness.",
      note: "Distinct from Top 8 Pomegranate Ginger" },

    { slug: "fresh-herbal-mint", name: "Fresh Herbal Mint", collection: "pipeline", season: "innovation",
      tag: "PIPELINE · WORKSHOP · M1",
      positioning: "Tea-herbal wellness · layered botanical",
      story: "Black tea and lavender over lemon, eucalyptus, and dual mint — tea-house sophistication with ginger warmth. Built for sodium chlorite.",
      note: "Workshop prototype M1 · retain study in progress" },
    { slug: "grove-mint", name: "Grove Mint", collection: "pipeline", season: "innovation",
      tag: "PIPELINE · WORKSHOP · M2",
      positioning: "Woody-herbal grove · floral lift",
      story: "Rosemary and palmarosa with ylang ylang over eucalyptus-spearmint — Mediterranean garden character.",
      note: "Workshop prototype M2 · retain study in progress" },
    { slug: "botanical-mint", name: "Botanical Mint", collection: "pipeline", season: "innovation",
      tag: "PIPELINE · WORKSHOP · M3",
      positioning: "Clinical botanical · therapeutic fresh",
      story: "Wintergreen and tea tree with rosewood, lavender, and lemongrass — gum-health botanical cue over clean peppermint.",
      note: "Workshop prototype M3 · wintergreen and tea tree retain review" },
    { slug: "immunity-mint", name: "Immunity Mint", collection: "pipeline", season: "innovation",
      tag: "PIPELINE · WORKSHOP · M4",
      positioning: "Wellness immunity cue · bright lift",
      story: "Lemon and ginger over clean peppermint — immunity positioning with bright lift, built for chlorite stability review.",
      note: "Workshop prototype M4 · distinct from Honey-Ginger presented concept" },
    { slug: "garden-mint", name: "Garden Mint", collection: "pipeline", season: "innovation",
      tag: "PIPELINE · WORKSHOP · M5",
      positioning: "Floral garden calm · everyday fresh",
      story: "Lavender and citronellal with sweet spearmint — garden-fresh calm, clean peppermint close.",
      note: "Workshop prototype M5 · lavender retain review in chlorite" },

    { slug: "electric-blue-chill", name: "Electric Blue Chill", collection: "genalpha", season: "future",
      tag: "GEN ALPHA · FUTURE", feel: "Scroll-stopping cool for the generation that films their routine.",
      positioning: "#FreshCheck · viral aesthetic",
      story: "Hyper-cool peppermint with electric sensory identity — belongs next to a gaming monitor.",
      note: "Mint-forward shell · color story drives shelf pop" },
    { slug: "cloud-matcha-mint", name: "Cloud Matcha Mint", collection: "genalpha", season: "future",
      tag: "GEN ALPHA · FUTURE", feel: "Clean-girl calm — café culture meets oral care.",
      positioning: "TikTok clean aesthetic",
      story: "Soft matcha creaminess with airy spearmint — gentle, photogenic, wellness-native.",
      note: "Distinct from pipeline Fresh Herbal Mint" },
    { slug: "y2k-bubblegum-mint", name: "Y2K Bubblegum Mint", collection: "genalpha", season: "future",
      tag: "GEN ALPHA · FUTURE", feel: "Ironic nostalgia — fun first, fresh always.",
      positioning: "Limited-edition drop",
      story: "Playful bubblegum sweetness snapped shut by crisp peppermint.",
      note: "Distinct from RW Orange Creamsicle" },
    { slug: "astro-peppermint", name: "Astro Peppermint", collection: "genalpha", season: "future",
      tag: "GEN ALPHA · FUTURE", feel: "Night-owl power-up — cosmic cool for gamers.",
      positioning: "Night gaming · extreme cool",
      story: "Dark, intense peppermint with star-level cooling — a boost, not a chore.",
      note: "Distinct from MW Peppermint Mocha" },
    { slug: "sparkling-vanilla-fizz", name: "Sparkling Vanilla Fizz", collection: "genalpha", season: "future",
      tag: "GEN ALPHA · FUTURE", feel: "Soda-fountain fantasy — treat-yourself without sugar.",
      positioning: "Soda-shop revival · festive LE",
      story: "Vanilla sparkle with a mint snap finish — malt-shop energy for the sparkling-water generation.",
      note: "Distinct from pipeline Garden Mint · soda-shop positioning" }
  ];

  function bySlug(slug) {
    return concepts.filter(function (c) { return c.slug === slug; })[0];
  }

  function byCollection(id) {
    return concepts.filter(function (c) { return c.collection === id; });
  }

  /* Bottle photos sourced from therabreath.com (+ Walmart for Grapes Galore, not on TB site yet). */
  var PRODUCTION_BOTTLES = {
    "clean-mint": "clean-mint.jpg",
    "invigorating-icy-mint": "invigorating-icy-mint.jpg",
    "mild-mint": "mild-mint.jpg",
    "rainforest-mint": "rainforest-mint.jpg",
    "dazzling-mint": "dazzling-mint.jpg",
    "tingling-mint": "tingling-mint.jpg",
    "sparkle-mint": "sparkle-mint.jpg",
    "revitalizing-mint": "revitalizing-mint.jpg",
    "overnight-rinse": "overnight-rinse.png",
    "grapes-galore": "grapes-galore.jpg",
    "wacky-watermelon": "wacky-watermelon.png",
    "strawberry-splash": "strawberry-splash.png",
    "bubble-gum": "bubble-gum.jpg"
  };

  function hasImage(c) {
    if (!c) return false;
    if (c.collection === "production") return !!PRODUCTION_BOTTLES[c.slug];
    return true;
  }

  global.TFFPortfolio = {
    concepts: concepts,
    collections: COLLECTIONS,
    seasons: SEASONS,
    bySlug: bySlug,
    byCollection: byCollection,
    hasImage: hasImage,
    imageUrl: function (slugOrConcept) {
      var c = typeof slugOrConcept === "string" ? bySlug(slugOrConcept) : slugOrConcept;
      if (!c || !hasImage(c)) return null;
      if (c.collection === "production") {
        return "/assets/portfolio/production/" + PRODUCTION_BOTTLES[c.slug] + "?v=2";
      }
      return "/assets/portfolio/" + c.slug + ".jpg?v=8";
    }
  };
})(typeof window !== "undefined" ? window : global);